### ISSUE TITLE
Error: Trying to network (receive) unacceptable type (table)

### ISSUE THREAD

**Issue by Taurvi** [Fortune117/thehidden#2]
Console on both the server and client keep spamming this: Error: Trying to network (receive) unacceptable type (table)

**Comment by YourStalker** [comment]
Can this please be addressed :P

**Comment by YourStalker** [comment]
I've looked into this a bit more, all I've got so far was that its something in gamemode/, not in the rtv or vgui folders, which gets rid of some net messages that could have been the culprits.

**Comment by Darksleep** [comment]
i am also to trying to hunt this sneak lua error down riping apart lua file at a time going to be long night

**Comment by YourStalker** [comment]
Post any info on the topic you find here please.

Another thing is that for every player on it seems to print ever (roughly) 8 seconds. So the more players the more spam. I tried commenting out every net.start chunk but nothing stopped the errors.

**Comment by Darksleep** [comment]
ye it only happens when Players are on so i am going to empty my server and add bots to see what come out of it

**Comment by Darksleep** [comment]
Ok i done said test and with just one bot error showed it ulgly face

**Comment by YourStalker** [comment]
Found the two lines:
```
function PLY:SetEquipment( equip )
	self.Equipment[ 1 ] = equip
--	self:SetNWString( "Equipment1", equip )     -- This asshole
end

function PLY:SetEquipment2( equip )
	self.Equipment[ 2 ] = equip
	self:SetNWString( "Equipment2", equip )    -- And this asshole
end```

**Comment by YourStalker** [comment]
:-1:  It was backwards you dyslexic poop, putting a PR in a sec.

**Comment by Darksleep** [comment]
Great job death to Error: Trying to network (receive) unacceptable type (table)

**Comment by YourStalker** [comment]
Ok, added it here because idk how to make a seperate PR:
https://github.com/Fortune117/thehidden/pull/4

**Comment by Darksleep** [comment]
he was on hour ago

**Comment by Darksleep** [comment]
I can fully say that edit work going to do full test now

**Comment by Darksleep** [comment]
I dont get what point game fully working all you need to do is 
Edit sv_loadout.lua line 11
replace self:SetNWString( "Equipment1", equip ) with --  self:SetNWString( "Equipment1", equip )

**Comment by Darksleep** [comment]
find it being used on if self:GetNWString( "Equipment1", "nah" ) == name || self:GetNWString( "Equipment2", "nah" ) == name then in sh_loadout.lua

**Comment by YourStalker** [comment]
Yeah, the latter thing you posted is fine, thats just him using the NWString he declared. It was the declaration that was messed up.

**Comment by Darksleep** [comment]
mate of my andreblue playing with it now and going to try fix it

**Comment by Fortune117** [comment]
Hey guys, sorry about the late reply. I didn't even realize this discussion existed, I'm still new to github. I'll look into it!

**Comment by Darksleep** [comment]
hey Fortune just so you know it pimp and it fixed i or andreblue will just make pull request and it should work hidden servers will now be happy

**Comment by Fortune117** [comment]
function PLY:SetEquipment( equip )
-	self.Equipment[ 1 ] = equip
+	equip = self.Equipment[ 1 ]
 	self:SetNWString( "Equipment1", equip )
 end
 
 function PLY:SetEquipment2( equip )
-	self.Equipment[ 2 ] = equip
+	equip = self.Equipment[ 2 ]
 	self:SetNWString( "Equipment2", equip )
 end

If this was your solution, that's actually no going to fix it. Sure it prevents the error, but now equipment doesn't work. You're defining a parameter as an empty table value. Why on earth are you defining the parameter?

**Comment by YourStalker** [comment]
I was testing it out and poof the print was gone. I said above that I had no clue what self.Equipment[1] actually was but equip wasn't defined in the first place so I assumed that you meant to set a variable (equip) equal to whatever self.Equipment[1] is.

**Comment by YourStalker** [comment]
In your original code you were setting self.Equipment[1] to a nil value (equal).

**Comment by Fortune117** [comment]
I've fixed the error now. I'll update git.
